### ISSUE TITLE
Get rid of bower

### ISSUE THREAD

**Issue by ehrenmurdick** [ehrenmurdick/purescript-oak#22]
And npm. Use yarn for everything

https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by ehrenmurdick** [comment]
Bower is the default for purescript for apparently good reason

**Comment by roper79** [comment]
Have you considered Spago?

**Comment by ehrenmurdick** [comment]
Oh neat just checked it out. I'll reopen this issue!

PS seeing you here makes me wonder if you're trying to use oak? If so, use <1.0 for now, I'm in the middle of a big trip and can't fix the latest but the do syntax for html has a fundamental issue so I'll be reverting it soon.

**Comment by roper79** [comment]
Yes, I stumbled upon Oak and I love its simplicity, so I would like to play with it a little bit.

**Comment by suzumiyasmith** [comment]
The best practice now is `spago`.
install it with git clone and run `stack install` in project dir.
After long waiting, we could use
`spago bundle-app app.js` instead `pulp --watch browserify --to app.js` to build.
Add dependencies to `packages.dhall` and `spago.dhall`
For simplicity, you may use `parcel.js` for the next step. 
`parcel build index.html` or `parcel build app.js`.

**Comment by ehrenmurdick** [comment]
@suzumiyasmith awesome. I'll work on that when I finish up at my day job

**Comment by ehrenmurdick** [comment]
Hmm. I don't love the look of spago, honestly. The build process seems more convoluted. On a quick read through the readme, you have to make a separate js file and import your Main.purs there in order to embed it. 

One of the things that I was very deliberate about in Oak is that your Main.main can embed itself in the page. And that pulp browserify does all you need to get going.

My main user target for Oak is not existing Haskel pros, but js developers. I'm hoping to convert React and Vue users and the like...

Going to stay with bower for now.

**Comment by suzumiyasmith** [comment]
Actually you don't have to import Main as a js module.
spago bundle-app -t index.js
And include index.js in a HTML file 
Everything done.
